# Generated by Django 5.0.7 on 2024-08-07 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AppleHealthStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_of_birth", models.DateTimeField()),
                ("height", models.IntegerField()),
                ("body_mass", models.IntegerField()),
                ("body_fat_percentage", models.IntegerField()),
                ("biological_sex", models.CharField(max_length=10)),
                ("activity_move_mode", models.CharField(max_length=50)),
                ("step_count", models.IntegerField()),
                ("basal_energy_burned", models.IntegerField()),
                ("active_energy_burned", models.IntegerField()),
                ("flights_climbed", models.IntegerField()),
                ("apple_exercise_time", models.IntegerField()),
                ("apple_move_time", models.IntegerField()),
                ("apple_stand_hour", models.IntegerField()),
                (
                    "menstrual_flow",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("hk_workout_type_identifier", models.CharField(max_length=50)),
                ("heart_rate", models.IntegerField()),
                ("oxygen_saturation", models.IntegerField()),
                ("mindful_session", models.JSONField()),
                ("sleep_analysis", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
